import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const builtins = [...builtinModules, ...builtinModules.map((moduleName) => `node:${moduleName}`)];
const aliasPlugin = {
	name: "community-review-safe-aliases",
	setup(build) {
		build.onResolve({ filter: /^setimmediate$/ }, () => ({ path: new URL("./src/shims/setimmediate.ts", import.meta.url).pathname }));
		build.onResolve({ filter: /^immediate$/ }, () => ({ path: new URL("./src/shims/immediate.ts", import.meta.url).pathname }));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [aliasPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
